version: '3.1'

services:
  db:
    image: postgres:14.3
    restart: always
    tty: true
    volumes:
      - .pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=sample
    ports:
      - "5432:5432"